POST http://localhost:8080/predict_food
Content-Type: multipart/form-data; boundary=myBoundary123

--myBoundary123
Content-Disposition: form-data; name="image"; filename="nasigoreng"
Content-Type: image/jpeg

< ./test.jpeg
--myBoundary123--


###
POST http://localhost:8080/predict_nutrition
Content-Type: application/json

{
  "umur": 32,
  "jenis_kelamin": "laki-laki",
  "tinggi_badan": 150
}

###


